/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesTrackTraceRouteImport } from './routes/services/track-trace'
import { Route as ServicesDispatchRouteImport } from './routes/services/dispatch'
import { Route as ServicesCustomerSupportRouteImport } from './routes/services/customer-support'
import { Route as ServicesBillingRouteImport } from './routes/services/billing'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin/submissions.index'
import { Route as AdminSubmissionsIdRouteImport } from './routes/admin/submissions.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServicesTrackTraceRoute = ServicesTrackTraceRouteImport.update({
  id: '/track-trace',
  path: '/track-trace',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDispatchRoute = ServicesDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomerSupportRoute = ServicesCustomerSupportRouteImport.update({
  id: '/customer-support',
  path: '/customer-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBillingRoute = ServicesBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsIdRoute = AdminSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/services/billing': typeof ServicesBillingRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/dispatch': typeof ServicesDispatchRoute
  '/services/track-trace': typeof ServicesTrackTraceRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/services/billing': typeof ServicesBillingRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/dispatch': typeof ServicesDispatchRoute
  '/services/track-trace': typeof ServicesTrackTraceRoute
  '/admin': typeof AdminIndexRoute
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/services/billing': typeof ServicesBillingRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/dispatch': typeof ServicesDispatchRoute
  '/services/track-trace': typeof ServicesTrackTraceRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/services/billing'
    | '/services/customer-support'
    | '/services/dispatch'
    | '/services/track-trace'
    | '/admin/'
    | '/admin/submissions/$id'
    | '/admin/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/services/billing'
    | '/services/customer-support'
    | '/services/dispatch'
    | '/services/track-trace'
    | '/admin'
    | '/admin/submissions/$id'
    | '/admin/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/services/billing'
    | '/services/customer-support'
    | '/services/dispatch'
    | '/services/track-trace'
    | '/admin/'
    | '/admin/submissions/$id'
    | '/admin/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/services/track-trace': {
      id: '/services/track-trace'
      path: '/track-trace'
      fullPath: '/services/track-trace'
      preLoaderRoute: typeof ServicesTrackTraceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dispatch': {
      id: '/services/dispatch'
      path: '/dispatch'
      fullPath: '/services/dispatch'
      preLoaderRoute: typeof ServicesDispatchRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/customer-support': {
      id: '/services/customer-support'
      path: '/customer-support'
      fullPath: '/services/customer-support'
      preLoaderRoute: typeof ServicesCustomerSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/billing': {
      id: '/services/billing'
      path: '/billing'
      fullPath: '/services/billing'
      preLoaderRoute: typeof ServicesBillingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions/$id': {
      id: '/admin/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/admin/submissions/$id'
      preLoaderRoute: typeof AdminSubmissionsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSubmissionsIdRoute: typeof AdminSubmissionsIdRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSubmissionsIdRoute: AdminSubmissionsIdRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ServicesRouteChildren {
  ServicesBillingRoute: typeof ServicesBillingRoute
  ServicesCustomerSupportRoute: typeof ServicesCustomerSupportRoute
  ServicesDispatchRoute: typeof ServicesDispatchRoute
  ServicesTrackTraceRoute: typeof ServicesTrackTraceRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBillingRoute: ServicesBillingRoute,
  ServicesCustomerSupportRoute: ServicesCustomerSupportRoute,
  ServicesDispatchRoute: ServicesDispatchRoute,
  ServicesTrackTraceRoute: ServicesTrackTraceRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
